name: amplify_recipe
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  form_field_validator: ^1.1.0
  intl: ^0.18.1
  image_picker: ^1.0.1
  get_it: ^7.6.0
  isar: ^4.0.0-0
  isar_flutter_libs: ^4.0.0-0
  path_provider: ^2.0.15
  go_router: ^9.1.0
  uuid: ^3.0.7
  amplify_flutter: ^1.3.1
  amplify_auth_cognito: ^1.3.1
  amplify_api: ^1.3.2
  amplify_storage_s3: ^1.3.2
  amplify_push_notifications_pinpoint: ^1.3.1

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/